package come.tool.JDialog;

import org.come.MountShouHu.ShouHuDiaglog;
import java.util.HashMap;
import java.util.Map;

public class TiShiUtil
{
    public static final String QL = "ql";
    public static String ChongTuSkill;
    public static String lingkang;
    public static String lingskill;
    public static String lingfushi;
    public static String lingtupo;
    public static String SkillDiscatd;
    public static String lingDiscatd;
    public static String GoodDiscatd;
    public static String ClearAllGood;
    public static String SellAllGood;
    public static String KickOut;
    public static String Abdication;
    public static String BreakAway;
    public static String DeleteSkill;
    public static String DeleteQlSkill;
    public static String GemOff;
    public static String washPoint;
    public static String trans;
    public static String starCard;
    public static String starCardDeposit;
    public static String Release;
    public static String SHSXX;
    public static String ZQGZ;
    public static String childRearing;
    public static String PalKey;
    public static String confirm;
    public static String OpenLingXi;
    public static String XiLingXi;
    public static String CBGBuy;
    public static String SFCS;
    public static String Babyase;
    public static String Fmcz;
    public static String Practice;
    public static String DoLottery;
    public static String lingbaoOut;
    public static String CBG;
    public static String droplh;
    public static String buylianghao;
    public static String openStarCard;
    public static Map<String, TiShiChuLi> tishiMap;
    public static String palAddPet;
    public static String lingToPal;
    public static String palGetPet;
    public static String palGetLingbao;
    public static String palToBaby;
    public static String palGetBaby;
    public static String shouhu;
    public static String Zxpack;
    public static String YUE;
    public static String JIII;
    public static String DeleteXuanBao = "DeleteXuanBao"; // 添加删除玄宝的提示类型
    public static String closeWl = "closeWl";
    public static String  Lingua = "Lingua";
    static {

        TiShiUtil.ChongTuSkill = "chongtuskill";
        TiShiUtil.lingkang = "lingkang";
        TiShiUtil.lingskill = "lingskill";
        TiShiUtil.lingfushi = "lingfushi";
        TiShiUtil.lingtupo = "lingtupo";
        TiShiUtil.SkillDiscatd = "SkillDiscatd";
        TiShiUtil.lingDiscatd = "lingDiscatd";
        TiShiUtil.GoodDiscatd = "GoodDiscatd";
        TiShiUtil.ClearAllGood = "ClearAllGood";
        TiShiUtil.SellAllGood = "SellAllGood";
        TiShiUtil.KickOut = "KickOut";
        TiShiUtil.Abdication = "Abdication";
        TiShiUtil.BreakAway = "BreakAway";
        TiShiUtil.DeleteSkill = "DeleteSkill";
        TiShiUtil.DeleteQlSkill = "DeleteQlSkill";
        TiShiUtil.GemOff = "GemOff";
        TiShiUtil.washPoint = "washPoint";
        TiShiUtil.trans = "trans";
        TiShiUtil.starCard = "starCard";
        TiShiUtil.starCardDeposit = "starCardDeposit";
        TiShiUtil.Release = "Release";
        TiShiUtil.SHSXX = "SHSXX";
        TiShiUtil.ZQGZ = "ZQGZ";
        TiShiUtil.childRearing = "ChildRearing";
        TiShiUtil.PalKey = "PalKey";
        TiShiUtil.confirm = "confirm";
        TiShiUtil.OpenLingXi = "openlingxi";
        TiShiUtil.XiLingXi = "xilingxi";
        TiShiUtil.CBGBuy = "CBGBuy";
        TiShiUtil.SFCS = "SFCS";
        TiShiUtil.Babyase = "Babyase";
        TiShiUtil.Fmcz = "Fmcz";
        TiShiUtil.Practice = "Practice";
        TiShiUtil.DoLottery = "DoLottery";
        TiShiUtil.lingbaoOut = "lingbaoOut";
        TiShiUtil.CBG = "CBG";
        TiShiUtil.droplh = "droplh";
        TiShiUtil.buylianghao = "buylianghao";
        TiShiUtil.openStarCard = "openStarCard";
        TiShiUtil.tishiMap = new HashMap<>();
        TiShiUtil.palAddPet = "palAddPet";
        TiShiUtil.lingToPal = "lingToPal";
        TiShiUtil.palGetPet = "palGetPet";
        TiShiUtil.palGetLingbao = "palGetLingbao";
        TiShiUtil.palToBaby = "palToBaby";
        TiShiUtil.palGetBaby = "palGetBaby";
        TiShiUtil.shouhu = "shouhu";
        TiShiUtil.Zxpack = "zxpack";
        TiShiUtil.YUE = "YUE";
        TiShiUtil.JIII = "JIII";
        TiShiUtil.tishiMap.put(TiShiUtil.lingtupo, new LingTupoJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.lingskill, new LingSkillJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.lingfushi, new LingFuShiJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.GoodDiscatd, new GoodDiscatdJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.ClearAllGood, new ClearAllGoodJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.SellAllGood, new SellAllGoodJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.KickOut, new KickOutJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.Abdication, new AbdicationJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.BreakAway, new BreakAwayJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.lingkang, new LingKangJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.lingDiscatd, new LingDiscatdJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.SkillDiscatd, new SkillDiscatdJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.DeleteSkill, new DeleteSkillJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.DeleteQlSkill, new DeleteQlSkillJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.GemOff, new GemOffJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.washPoint, new washPointJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.trans, new TransJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.starCard, new StarCardJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.starCardDeposit, new StarCardDepositJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.Release, new ReleaseJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.childRearing, new ChildRearingJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.PalKey, new PalKeyJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.confirm, new ConfirmDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.CBGBuy, new CBGBuyJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.OpenLingXi, new OpenLxJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.XiLingXi, new XiLxJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.SFCS, new SFCSJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.Babyase, new BabyaseJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.Fmcz, new FmczJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.Practice, new PracticeJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.DoLottery, new DoLotteryJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.lingbaoOut, new LingbaoOut());
        TiShiUtil.tishiMap.put(TiShiUtil.CBG, new CBGJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.droplh, new DropLiangHaoJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.buylianghao, new BuyLiangHaoJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.openStarCard, new OpenStarCardJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.palAddPet, new PalAddPetJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.palGetPet, new PalGetPetJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.palGetLingbao, new LingGetPalJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.palGetBaby, new PalGetBabyJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.palToBaby, new PalToBabyJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.lingToPal, new LingToPalJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.shouhu, new ShouHuDiaglog());
        TiShiUtil.tishiMap.put(TiShiUtil.Zxpack, new ZxpackJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.SHSXX, new SHSXXJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.ZQGZ, new ZQGZJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.ChongTuSkill, new ChongTuJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.YUE, new YuekaJDialog());
        TiShiUtil.tishiMap.put(TiShiUtil.JIII, new JikaJDialog());
        tishiMap.put(QL,new QlJDialog());
        tishiMap.put(closeWl, new CloseWLSkillJDialog());
        tishiMap.put(Lingua, new LinguaJDialog());
        tishiMap.put(DeleteXuanBao, new DeleteXuanBaoJDialog()); // 添加删除玄宝的处理类
    }
}
