package org.come.action;

import org.come.annex.Tournaments.Other.TournamentsControl;
import org.come.control.*;
import org.come.MountShouHu.ShouHuControl;
import org.come.npc.SkillLearn3;
import org.come.npc.SkillLearn2;
import org.come.bean.Account_BindingControl;
import org.come.bean.AreaStatuesControl;
import org.come.bean.Account_LoginControl;
import org.cbg.control.SearchBuyResultControl;
import org.cbg.control.SearchColectionStatuesResultControl;
import org.cbg.control.SearchDeleteMessageResultControl;
import org.cbg.control.SearchCollectionQueryControl;
import org.cbg.control.SearchMesResultControl;
import org.cbg.control.SearchMyGoodsResultControl;
import org.cbg.control.SearchDesignatedPurchaseResultControl;
import org.cbg.control.SearchMyOrderResultControl;
import org.cbg.control.SearchConsignmentGoodsResultControl;
import org.cbg.control.SearchGoodsResultControl;
import org.come.annex.Tournaments.Other.TournamentsControl;
import org.come.control.festival.GiveGoodsControl;
import org.come.control.festival.HatchValueControl;
import org.come.npc.Gotochangan;
import org.come.npc.GetOut;
import org.come.npc.FlightChessTP;
import org.come.npc.Sleep;
import org.come.npc.PetConversion;
import org.come.npc.Creeps;
import org.come.npc.GangInto;
import org.come.npc.DBExp;
import org.come.npc.SkillLearn;
import org.come.socket.AgreementUtil;
import org.come.until.NpcMenuUntil;
import org.come.until.MessageProcessUntil;
import org.come.login.LoginControl;

import java.util.HashMap;

import io.netty.channel.ChannelHandlerContext;
import java.util.Map;

public class MapAction
{
    public static Map<String, ChannelHandlerContext> nettyAction;
    public static Map<String, Boolean> flagAction;
    public static Map<String, FromServerAction> serverAction;
    public static Map<String, NpcMenuAction> npcmenuAction;
    public static ServerMesControl mesControl;
    
    static {
        MapAction.nettyAction = new HashMap<>();
        MapAction.flagAction = new HashMap<>();
        MapAction.serverAction = new HashMap<>();
        MapAction.npcmenuAction = new HashMap<>();
        MapAction.mesControl = new ServerMesControl();
        MapAction.serverAction.put("laddArena", new TeamArenaControl("laddArena"));
        LoginControl loginControl = new LoginControl();
        MapAction.serverAction.put("rigistersuccess", loginControl);
        MapAction.serverAction.put("AuctionGoods", new AuctionGoodsControl());
        MapAction.serverAction.put("rigistererror", loginControl);
        MapAction.serverAction.put("loginsuccess", loginControl);
        MapAction.serverAction.put("loginerror", loginControl);
        MapAction.serverAction.put("createsuccess", loginControl);
        MapAction.serverAction.put("createerror", loginControl);
        MapAction.serverAction.put("version", new VersionControl());
        MapAction.serverAction.put("babycustoday", new BabycustodayControl());
        MapAction.serverAction.put("intogame", new IntoGameControl());
        MapAction.serverAction.put("npcdialog", new NPCDialogControl());
        MapAction.serverAction.put("npc", new NPCDialogControl2());
        MapAction.serverAction.put("fig1", new FightingroundControl());
        MapAction.serverAction.put("fig5", new FightingrounddealControl());
        MapAction.serverAction.put("fig4", new FightingroundendControl());
        MapAction.serverAction.put("fig7", new BattleStateControl());
        MapAction.serverAction.put("fig6", new BattleEndControl());
        MapAction.serverAction.put("battleconnection", new BattleConnectionControl());
        MapAction.serverAction.put("fightinglingbao", new BattleLingBaoLiangControl());
        MapAction.serverAction.put("movd", new MovedControl());
        MapAction.serverAction.put(MessageProcessUntil.prompt, new PromptControl());
        MapAction.serverAction.put(MessageProcessUntil.pet, new PetControl());
        MapAction.serverAction.put(MessageProcessUntil.marry, new MarryControl());
        MapAction.serverAction.put("fig9", new FightInfolControl());
        MapAction.serverAction.put(MessageProcessUntil.monster, new MonsterRefreshControl());
        MapAction.serverAction.put("upRoleShow", new UpRoleShowControl());
        MapAction.serverAction.put("chat", new NChatControl());
        MapAction.serverAction.put(MessageProcessUntil.stall, new StallControl());
        MapAction.serverAction.put(MessageProcessUntil.stallstate, new StallStateControl());
        MapAction.serverAction.put(MessageProcessUntil.asset, new AssetControl());
        MapAction.serverAction.put(MessageProcessUntil.titlelist, new RoleChangeAppellationControl());
        MapAction.serverAction.put(MessageProcessUntil.gettitlelist, new GetRoleTilelistAppellationControl());
        MapAction.serverAction.put(MessageProcessUntil.racialtransformation, new RoleConversionControl());
        MapAction.serverAction.put(MessageProcessUntil.mount, new MountFunctionControl());
        MapAction.serverAction.put(MessageProcessUntil.car, new CarFunctionControl());
        MapAction.serverAction.put(MessageProcessUntil.friend, new FriendServerControl());
        MapAction.serverAction.put(MessageProcessUntil.friendchat, new FriendChatControl());
        MapAction.serverAction.put(MessageProcessUntil.fly, new FlyFunctionControl());
        MapAction.serverAction.put("addgood", new AddGoodControl());
        MapAction.serverAction.put(MessageProcessUntil.baby, new BabyControl());
        MapAction.serverAction.put(MessageProcessUntil.marry, new MarryControl());
        MapAction.serverAction.put("gangchange", new GangChangeControl());
        MapAction.serverAction.put("intogang", new IntogangControl());
        MapAction.serverAction.put("ganglist", new GanglistControl());
        MapAction.serverAction.put("gangstate", new GangStateControl());
        MapAction.serverAction.put("bangtz", new BangCControl());
        MapAction.serverAction.put("givemoney", new GangGiveMoneyControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu80(), new GangsGuardControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu81(), new GangsGuardControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu82(), new EggControl());
        MapAction.serverAction.put("userretreat", new UserretreatControl());
        MapAction.serverAction.put("intogame", new IntoGameControl());
        MapAction.serverAction.put(MessageProcessUntil.applypay, new ApplyPayControl());
        MapAction.serverAction.put(MessageProcessUntil.USER_DIANDANG, new GetPawmControl());
        MapAction.serverAction.put("rolelevelup", new RoleLevelUpControl());
        MapAction.serverAction.put("move", new MoveControl());
        MapAction.serverAction.put(MessageProcessUntil.changerolename, new ChangerolenameControl());
        MapAction.serverAction.put(MessageProcessUntil.pong, new ServerPongControl());
        MapAction.serverAction.put("taskN", new TaskNControl());
        MapAction.serverAction.put("middle", new MiddleControl());
        MapAction.serverAction.put(MessageProcessUntil.obtainarticle, new RewardHallControl());
        MapAction.serverAction.put(MessageProcessUntil.drawnitems, new RewardHallControl());
        MapAction.serverAction.put(MessageProcessUntil.drawnitemsfail, new RewardHallControl());
        MapAction.serverAction.put(MessageProcessUntil.pankinglist, new RankingListControl());
        MapAction.serverAction.put("enterGame", new EnterGameControl());
        MapAction.serverAction.put("tip", new ReturnTipControl());
        MapAction.serverAction.put("bookofchalg", new ReturnTipControl());
        MapAction.serverAction.put("getfivemsg", new QuackGameControl());
        MapAction.serverAction.put("extrattroper", new ExtraAttrOperControl());
        MapAction.serverAction.put("1", new PackRecordControl());
        MapAction.serverAction.put("richm", new RichMonitorControl());
        MapAction.serverAction.put("searcahChatRoleId", new SearcahChatControl());
        MapAction.serverAction.put("shop", new ShopControl());
        MapAction.serverAction.put("shopGood", new ShopGoodsControl());
        MapAction.serverAction.put("shopPrice", new ShopPriceControl());
        MapAction.serverAction.put("TransState", new TransStateControl());
        MapAction.serverAction.put("TransGood", new TransGoodControl());
        MapAction.serverAction.put("fig8", new FightQlControl());
        MapAction.npcmenuAction.put("npcdialog", new BangBattleControl());
        MapAction.npcmenuAction.put("菜单", new NpcMenuControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.SKILL, new SkillLearn());
        MapAction.npcmenuAction.put(NpcMenuUntil.DBEXP, new DBExp());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMarry(), new MarryInfromantsControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getUnMaary(), new MarryInfromantsControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMakelove(), new MakeLoveControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getShowrolesummingfaithful(), new RoleSumminCloseControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getCurerolesumming(), new RoleSumminCloseControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu39(), new GangInto());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu48(), new Creeps());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu15(), new PetConversion());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu9(), new Sleep());
        MapAction.npcmenuAction.put(NpcMenuUntil.TP, new FlightChessTP());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu51(), new SelectOptionControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMenu52(), new CompulsoryDivorceControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.GETOUT, new GetOut());
        MapAction.npcmenuAction.put(NpcMenuUntil.GOTO, new Gotochangan());
        MapAction.npcmenuAction.put(NpcMenuUntil.JG, new JieGuaControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.LOTTERY, new GangOperationControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.THROWIN, new GangOperationControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.CHALLENGE, new SurfaceAssemblyControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.EXCHANGEVAL, new ExchangeValueControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.WILLENTER, new ExchangeValueControl());
        MapAction.npcmenuAction.put("我来助你一孵之力（需提交一个物品）", new GiveAHandcontrol());
        MapAction.npcmenuAction.put("战力恢复", new StarCardSupplement());
        MapAction.serverAction.put("hatchvalue", new HatchValueControl());
        MapAction.serverAction.put("givegoods", new GiveGoodsControl());
        MapAction.serverAction.put("CBGSearch1", new SearchGoodsResultControl());
        MapAction.serverAction.put("CBGSearch2", new SearchConsignmentGoodsResultControl());
        MapAction.serverAction.put("CBGSearch3", new SearchMyOrderResultControl());
        MapAction.serverAction.put("CBGSearch4", new SearchDesignatedPurchaseResultControl());
        MapAction.serverAction.put("CBGSearch5", new SearchMyGoodsResultControl());
        MapAction.serverAction.put("CBGSearch6", new SearchMesResultControl());
        MapAction.serverAction.put("CBGSearch7", new SearchCollectionQueryControl());
        MapAction.serverAction.put("CBGMes", new SearchDeleteMessageResultControl());
        MapAction.serverAction.put("CBGCollect", new SearchColectionStatuesResultControl());
        MapAction.serverAction.put("CBGBuy", new SearchBuyResultControl());
        MapAction.serverAction.put("DUELBOARD", new DuelBoardControl());
        MapAction.serverAction.put("PhoneNumberIsNoGet", new PhoneNumberIsNoGetControl());
        MapAction.serverAction.put("PhoneBang", new PhoneBangControl());
        MapAction.serverAction.put("UnPhoneBang", new UnPhoneBangControl());
        MapAction.serverAction.put("scene", new SceneControl());
        MapAction.serverAction.put("Getvipgradepack", new GetvipgradepackControl());
        MapAction.serverAction.put("Paydaygradepay", new PaydaygradepayControl());
        MapAction.serverAction.put("Dayforweekgradeget", new DayforweekgradegetControl());
        MapAction.serverAction.put("Dayforoneget", new DayforonegetControl());
        MapAction.serverAction.put("LimitedTimeShop", new LimitedTimeShopControl());
        MapAction.serverAction.put("chongjipackget", new ChongjipackgetControl());
        MapAction.serverAction.put("RETAREA", new RetareaControl());
        MapAction.serverAction.put("UidAndQidForRole", new UidAndQidForRoleControl());
        MapAction.serverAction.put("PhoneNumber", new PhoneNumberControl());
        MapAction.serverAction.put("team1", new TeamControl());
        MapAction.serverAction.put("oneArena", new OneArenaControl());
        MapAction.serverAction.put("LOGINVERSION", new VersionControl());
        MapAction.serverAction.put("ACCOUNT_LOGIN", new Account_LoginControl());
        MapAction.serverAction.put("AREASTATUES", new AreaStatuesControl());
        MapAction.serverAction.put("ACCOUNT_BINDING", new Account_BindingControl());
        MapAction.serverAction.put("teamArena", new TeamArenaControl("teamArena"));
        MapAction.serverAction.put("vicon", new ViconControl());
        MapAction.serverAction.put("labor", new LaborControl());
        MapAction.serverAction.put("hjsl", new HjslControl());
        MapAction.serverAction.put("rolechange", new RolechangeControl());
        MapAction.serverAction.put("lingxi", new LxControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.FMSKILL, new SkillLearn2());
        MapAction.npcmenuAction.put(NpcMenuUntil.XPSKILL, new SkillLearn3());
        MapAction.serverAction.put("rolechange1", new RolexingpanControl());
        MapAction.serverAction.put("qd", new QianDaoControl());
        MapAction.serverAction.put("QMJC", new QmjcControl());
        MapAction.serverAction.put("sellxianyu", new SellXianYuControl());
        MapAction.serverAction.put("shaoxiang", new ShaoXiangControl());
        MapAction.serverAction.put("lottery", new LotteryControl());
        MapAction.serverAction.put("selllianghao", new SellLiangHaoControl());
        MapAction.serverAction.put("HDX", new HDXControl());
        MapAction.serverAction.put("GUA", new GUAControl());
        MapAction.serverAction.put("AutoTask", new AutoTaskControl());
        MapAction.serverAction.put("shouhuPMxy", new ShouHuControl());
        MapAction.serverAction.put("zxpack", new ZxpackControl());
        serverAction.put(AgreementUtil.ROLEACHIEVE, new AchievemControl());
        serverAction.put(AgreementUtil.ZXDOOD, new ZxGoodsControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getDelskill(), new DelSkillMenuControl());
        MapAction.npcmenuAction.put(NpcMenuUntil.getMONEYCQ(), new QZControl());
        serverAction.put(AgreementUtil.ROLEDAYDRAW, new DayDrawControl());
        serverAction.put(AgreementUtil.xydjls, new XYDJControl());
        serverAction.put("tournamentsData", new TournamentsControl());
    }
}
