package org.come.until;

public class MessageProcessUntil
{
    public static String petoperation;
    public static String USER_DIANDANG;
    public static String USER_LOGIN;
    public static String LOGIN_SUCCESS;
    public static String RESGITER_SUCCESS;
    public static String CREATEROLE;
    public static String CREATEROLE_ERROR;
    public static String ServerMes;
    public static String createrole;
    public static String packchange;
    public static String eshop;
    public static String pet;
    public static String mount;
    public static String car;
    public static String buy;
    public static String groupApply;
    public static String groupaccess;
    public static String friend;
    public static String addfriend;
    public static String friendchat;
    public static String shop;
    public static String changemap;
    public static String give;
    public static String trans;
    public static String petcarry;
    public static String petchange;
    public static String packlock;
    public static String packgift;
    public static String skilllearn;
    public static String creepsfight;
    public static String monster;
    public static String Summonpet;
    public static String npccompose;
    public static String rolechange;
    public static String summonpet;
    public static String titlelist;
    public static String gettitlelist;
    public static String npccure;
    public static String givemoney;
    public static String marry;
    public static String monsterstate;
    public static String prompt;
    public static String titlechange;
    public static String buymingchao;
    public static String racialtransformation;
    public static String deletefriend;
    public static String baby;
    public static String applypay;
    public static String changerolename;
    public static String pong;
    public static String stall;
    public static String asset;
    public static String stallstate;
    public static String updatemonsters;
    public static String obtainarticle;
    public static String drawnitems;
    public static String drawnitemsfail;
    public static String pankinglist;
    public static String skilllearn2;
    public static String rolechange1;
    public static String fly;
    public static String sellxianyu;
    
    static {
        MessageProcessUntil.petoperation = "petoperation";
        MessageProcessUntil.USER_DIANDANG = "pawn";
        MessageProcessUntil.USER_LOGIN = "USER_LOGIN";
        MessageProcessUntil.LOGIN_SUCCESS = "loginsuccess";
        MessageProcessUntil.RESGITER_SUCCESS = "rigistersuccess";
        MessageProcessUntil.CREATEROLE = "createrole";
        MessageProcessUntil.CREATEROLE_ERROR = "createerror";
        MessageProcessUntil.ServerMes = "ServerMes";
        MessageProcessUntil.createrole = "createrole";
        MessageProcessUntil.packchange = "packchange";
        MessageProcessUntil.eshop = "eshop";
        MessageProcessUntil.pet = "pet";
        MessageProcessUntil.mount = "mount";
        MessageProcessUntil.car = "car";
        MessageProcessUntil.buy = "buy";
        MessageProcessUntil.groupApply = "groupApply";
        MessageProcessUntil.groupaccess = "groupaccess";
        MessageProcessUntil.friend = "friend";
        MessageProcessUntil.addfriend = "addfriend";
        MessageProcessUntil.friendchat = "friendchat";
        MessageProcessUntil.shop = "shop";
        MessageProcessUntil.changemap = "changemap";
        MessageProcessUntil.give = "give";
        MessageProcessUntil.trans = "trans";
        MessageProcessUntil.petcarry = "petcarry";
        MessageProcessUntil.petchange = "shuanimabipetchange";
        MessageProcessUntil.packlock = "packlock";
        MessageProcessUntil.packgift = "packgift";
        MessageProcessUntil.skilllearn = "skilllearn";
        MessageProcessUntil.creepsfight = "creepsfight";
        MessageProcessUntil.monster = "monster";
        MessageProcessUntil.Summonpet = "Summonpet";
        MessageProcessUntil.npccompose = "npccompose";
        MessageProcessUntil.rolechange = "rolechange";
        MessageProcessUntil.summonpet = "summonpet";
        MessageProcessUntil.titlelist = "titlelist";
        MessageProcessUntil.gettitlelist = "gettitlelist";
        MessageProcessUntil.npccure = "npccure";
        MessageProcessUntil.givemoney = "givemoney";
        MessageProcessUntil.marry = "marry";
        MessageProcessUntil.monsterstate = "monsterstate";
        MessageProcessUntil.prompt = "prompt";
        MessageProcessUntil.titlechange = "titlechange";
        MessageProcessUntil.buymingchao = "buymingchao";
        MessageProcessUntil.racialtransformation = "racialtransformation";
        MessageProcessUntil.deletefriend = "deletefriend";
        MessageProcessUntil.baby = "baby";
        MessageProcessUntil.applypay = "applypay";
        MessageProcessUntil.changerolename = "changerolename";
        MessageProcessUntil.pong = "pong";
        MessageProcessUntil.stall = "stall";
        MessageProcessUntil.asset = "asset";
        MessageProcessUntil.stallstate = "stallstate";
        MessageProcessUntil.updatemonsters = "updatemonsters";
        MessageProcessUntil.obtainarticle = "obtainarticle";
        MessageProcessUntil.drawnitems = "drawnitems";
        MessageProcessUntil.drawnitemsfail = "drawnitemsfail";
        MessageProcessUntil.pankinglist = "pankinglist";
        MessageProcessUntil.skilllearn2 = "skilllearn2";
        MessageProcessUntil.rolechange1 = "rolechange1";
        MessageProcessUntil.fly = "fly";
        MessageProcessUntil.sellxianyu = "sellxianyu";
    }
}
