package org.come.protocol;

import java.util.HashMap;

import come.tool.Good.*;
import org.come.action.lingbao.UpdateXuanAction;
import org.come.action.mount.*;
import org.come.action.qzcunqu.QZCUNQUMoneyAction;
import org.come.action.jiegua.JieGuaAction;
import org.come.action.lottery.HDXRoleAction;
import org.come.action.role.*;
import org.come.action.selllianghao.SellLiangHaoAction;
import org.come.action.zxpack.ZxpackNineAction;
import org.come.action.lotterynine.LotteryNineAction;
import org.come.action.lianghao.LiangHaoAction;
import org.come.action.vip.AutoTaskAction;
import org.come.action.shaoxiang.ShaoXiangAction;
import org.come.action.sellxianyu.SellXianYuAction;
import org.come.action.sys.updateXianyuAction;
import org.come.action.login.Account_Login;
import org.come.action.lottery.LotteryRoleAction;
import org.come.action.sys.expAddAction;
import org.come.gmshop.GMshopItemAction;
import org.come.qiandao.QianDaoAction;
import org.come.action.gl.LxAction;
import org.come.action.gl.GoodsExchangeAction;
import come.tool.hjsl.HjslAction;
import org.come.action.gl.EggAction;
import org.come.action.gl.FindDropAction;
import org.come.action.pay.Payreturn;
import org.come.extInterface.sale.GoodsBuy;
import org.come.extInterface.SaleGoodsStatues;
import org.come.extInterface.SalesGoodsChangeOrder;
import come.tool.Scene.VIconAction;
import come.tool.Scene.LaborAction;
import come.tool.teamArena.TeamArenaAction;
import come.tool.oneArena.OneArenaAction;
import org.come.action.sys.ConfirmAciton;
import org.come.action.sys.FindWayAction;
import come.tool.newTeam.TeamApplyListAction;
import come.tool.newTeam.TeamOperateAction;
import come.tool.newTeam.TeamStateAction;
import come.tool.newTeam.TeamApplyAction;
import come.tool.newTeam.TeamCreateAction;
import come.tool.newTeam.TeamEnlistAction;
import org.come.action.buy.ShopPriceAction;
import come.tool.Scene.SceneAction;
import org.come.action.vip.LimitedTimeLshopAction;
import org.come.action.vip.PayLJGradeSureAction;
import org.come.action.vip.PayLJGradePayAction;
import org.come.action.vip.ChongJiPackOpenAction;
import org.come.action.vip.ChongJiPackSureAction;
import org.come.action.vip.ChongJiPackGetAction;
import org.come.action.vip.DayForOneSureAction;
import org.come.action.vip.DayForOneGetAction;
import org.come.action.vip.DayForWeekGradeSureAction;
import org.come.action.vip.DayForWeekGradeGetAction;
import org.come.action.vip.PayDayGradeSureAction;
import org.come.action.vip.PayDayGradePayAction;
import org.come.action.vip.VipGradeSureAction;
import org.come.action.vip.GetVipGradePackAction;
import org.come.action.phone.PhoneNumberIsNoGetAction;
import org.come.action.phone.UnPhoneBangAction;
import org.come.action.phone.PhoneBangAction;
import org.come.action.fight.FightQlAction;
import come.tool.newTask.TaskAction;
import org.come.action.monitor.MonitorAction;
import come.tool.newTrans.TransGoodAction;
import come.tool.newTrans.TransStateAction;
import org.come.action.monster.ClickMonsterAction;
import org.come.action.sale.GoodsBackAction;
import org.come.action.sale.GoodsBuyAction;
import org.come.action.sale.GoodsShelfAction;
import org.come.action.sale.MyWaresSearchAction;
import org.come.action.sale.GoodsSearchAction;
import org.come.action.sale.MessageControlAction;
import org.come.action.sale.CollectionControlAction;
import org.come.action.sale.GoodsControlAction;
import org.come.action.sale.CollectionSearchAction;
import org.come.action.sale.MessageSearchAction;
import org.come.action.sale.MyGoodsSearchAction;
import org.come.action.sale.AppointBuyAction;
import org.come.action.sale.MyOrderSearchAction;
import org.come.action.buy.NpcShopAction;
import org.come.action.wechat.SearchChatRecordeAction;
import org.come.action.wechat.SearcahChatRoleNameAction;
import org.come.action.wechat.SearcahChatRoleIdAction;
import org.come.action.chat.ChatAction;
import org.come.action.rich.RichMonitorAction;
import org.come.action.festival.HatchaddAction;
import org.come.action.festival.HatchvalueAction;
import org.come.action.suit.QualityCAciton;
import org.come.action.suit.SuitComposeAction;
import org.come.action.exchange.ExchangeGoodsAction;
import org.come.action.lottery.LotteryAction;
import come.tool.PK.RefusechalgAction;
import come.tool.PK.BookofchalgAction;
import org.come.action.sys.enterGameAction;
import org.come.action.pack.PackRecordAction;
import org.come.action.buy.BuyShopAction;
import come.tool.teamArena.LadderArenaAction;
import org.come.action.sys.OrderByRoleAction;
import org.come.action.sys.AccountStopAction;
import org.come.action.sys.BindingMobileAction;
import org.come.action.reward.ThrowinarticleAction;
import org.come.action.summoning.itemAction;
import org.come.action.reward.DrawnitemsAction;
import org.come.action.reward.ObtainarticleAction;
import org.come.action.monster.AddMonsterAction;
import come.tool.Stall.StallGetAction;
import come.tool.Stall.StallBuyAction;
import come.tool.Stall.StallUpdateAction;
import come.tool.Stall.StallListingAction;
import come.tool.Stall.StallAction;
import org.come.action.gang.GangBattleAction;
import org.come.action.gang.GangMonitorAction;
import org.come.action.baby.UpdaBabyAction;
import org.come.action.fight.QuoteOutAction;
import org.come.action.fight.PrisonAction;
import org.come.action.sys.MiddleAction;
import org.come.action.npc.NPCDialogAction;
import org.come.action.lingbao.UpdateLingAction;
import org.come.action.baby.BabyCustodayAction;
import org.come.action.baby.BabyBornAction;
import org.come.action.bring.UnMarryAction;
import org.come.action.baby.BabyAction;
import org.come.action.Fly.FlyGetAction;
import org.come.action.Keju.KejuhuidaAction;
import org.come.action.Keju.KejuAction;
import org.come.action.Fly.FlyAction;
import org.come.action.Fly.FlyUpdateAction;
import org.come.action.fight.FightingRoundAction;
import org.come.action.buy.BuyMingChaoAction;
import org.come.action.summoning.PetAlchemyAction;
import org.come.action.gang.GangGiveMoneyAction;
import org.come.action.npc.NpcCureAction;
import org.come.action.fight.FightingendAction;
import org.come.action.fight.FightingForeseeAction;
import org.come.action.fight.FightbattleConnectionAction;
import org.come.action.fight.FightRoundAction;
import org.come.action.summoning.SummonPetAction;
import org.come.action.summoning.PetReleaseFPAction;
import org.come.action.summoning.PetReleaseAction;
import org.come.action.suit.WitchComposeAction;
import org.come.action.npc.NpcComposeAction;
import org.come.action.summoning.PetInfoAction;
import org.come.action.bring.MakeLoveAction;
import org.come.action.bring.MarryAction;
import org.come.action.pack.PackGiftAction;
import org.come.action.pack.PackLockAction;
import org.come.action.title.GetTitleListAction;
import org.come.action.title.TitleListAction;
import org.come.action.title.TitleChangeAction;
import org.come.action.title.TitleExpireAction;
import org.come.action.summoning.PetChangeSkillAction;
import org.come.action.summoning.PetChangeAction;
import org.come.action.pawn.RetrieveAction;
import org.come.action.pawn.PawnAction;
import org.come.action.gang.GangChangeAction;
import org.come.action.gang.GangAppointAction;
import org.come.action.gang.GangRefuseAction;
import org.come.action.gang.GangAgreeAction;
import org.come.action.gang.GangShotAction;
import org.come.action.give.GiveAction;
import org.come.action.gang.GangListAction;
import org.come.action.gang.GangRetreatrestAction;
import org.come.action.gang.GangRetreatAction;
import org.come.action.gang.GangApplyAction;
import org.come.action.gang.GangCreateAction;
import org.come.action.sys.ChangeMapAction;
import org.come.action.chat.FriendChatAction;
import org.come.action.friend.DeleteFriendAction;
import org.come.action.friend.AddFriendAction;
import org.come.action.friend.FriendAction;
import org.come.action.pack.PackChangeAction;
import org.come.action.summoning.PetDepositAction;
import org.come.action.gang.IntoGangAction;
import org.come.action.sys.RegisterAction;
import org.come.action.chooseRole.SelectRoleByArea;
import org.come.action.chooseRole.GetRoleByQuid;
import org.come.action.phonenumber.PhoneAction;
import org.come.extInterface.GetInlinePeople;
import org.come.action.version.PhoneVersion;
import org.come.action.jp.AuctionAction;
import org.come.extInterface.Readtxt;
import org.come.extInterface.GetVersion;
import org.come.action.login.shouji_long;
import org.come.action.phonenumber.CheckPhoneAction;
import org.come.action.sys.LoginAction;
import org.come.action.IAction;
import java.util.Map;

public class ParamTool
{
    public static final Map<String, IAction> ACTION_MAP;
    public static final Map<String, IAction> ACTION_MAP2;
    
    public static void handles() {
        try {
            if ("MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwA5bvsBpZkn6uNFgBdxT\r\ng939ldFNJ3B+K7WqhXxWVsLZj64cUKDAnm7WPkRgdrfqp7rfgfdCeGHAaSd2/j4P\r\nx4ywotMCuVIcjxIZTwS+pSZMaNLt9JC5qygYoiPXV4U2GsOA2UfMiLcoO04yfAV4\r\n/vACGNNLhonZ2Y/0q58g32F3VDmNmD7jSrcHREWB3n87qGgxgGCh8LCXaVjpEFoo\r\nfO3j/MsMlyXbs0gZseFzS8JjDB+v6VImL1eu6amW82bfEVXt6eKcrWNpPRXFAac5\r\n031X9ppcrCXh0W2OB+4qtp8Fuu8Z8aEtA91BFmne2reDcrfJEnRmj0S1CK+tzYwG\r\nDdhlY5bzPMkvuta6Lpt8wF/N3yhI6Sgs9P6K5rlBJCrI6iIQsSchyZJEjKir1lWv\r\n11Icu575q0q36JhDwmtT9Op/5xhAZykvh28eNPigd/VcxkwykE0ekN06ElsDDs+X\r\nk+uzO0Uo/ReX7j3kyUGla6h9L5bpS+7M4gx/aQcYCbBXPqxv6+eeHErj2AoG5H8R\r\nv3UmlKX3kvLpLYV2UG6ub5B9nCRJPC98S/RTZN8Jes8tUg54N6/9PdJndwdCQsUv\r\ne1hDvynUKu9/J6YNGqiS2efvHOCL+HFk3l6VAywZRtUxuzDh8gY+U2MiCrMqlRA/\r\n8/Ad1wL8I+LO2E+EF9zPgcMCAwEAAQ==" != null) {}
        }
        catch (Exception e) {
            System.exit(0);
        }
        IAction action1 = new LoginAction();
        ParamTool.ACTION_MAP.put("login", action1);

        IAction action1023= new UpdateXuanAction();
        ACTION_MAP.put(AgreementUtil.updatexuan, action1023);

        IAction action2 = new CheckPhoneAction();
        ParamTool.ACTION_MAP.put(AgreementUtil.checkPhone, action2);
        IAction action3 = new shouji_long();
        ParamTool.ACTION_MAP.put("sjlogin", action3);
        IAction action4 = new GetVersion();
        ParamTool.ACTION_MAP.put("getVersion_inter", action4);
        IAction action5 = new Readtxt();
        ParamTool.ACTION_MAP.put("readtxt_inter", action5);
        IAction action6 = new denglushibai();
        ParamTool.ACTION_MAP.put("loginerror", action6);
        IAction auctionAction = new AuctionAction();
        ParamTool.ACTION_MAP.put("auctionGoods", auctionAction);
        IAction action7 = new PhoneVersion();
        ParamTool.ACTION_MAP.put("phoneVersion", action7);
        IAction action8 = new GetInlinePeople();
        ParamTool.ACTION_MAP.put("getInlinePeople_inter", action8);
        IAction action9 = new PhoneAction();
        ParamTool.ACTION_MAP.put("PhoneNumber", action9);
        IAction action10 = new GetRoleByQuid();
        ParamTool.ACTION_MAP.put("UidAndQidForRole", action10);
        IAction action11 = new SelectRoleByArea();
        ParamTool.ACTION_MAP.put("GETAREA", action11);
        IAction action12 = new RegisterAction();
        ParamTool.ACTION_MAP.put("register", action12);
        IAction action13 = new CreateRoleAction();
        ParamTool.ACTION_MAP.put("createrole", action13);
        IAction action14 = new IntoGangAction();
        ParamTool.ACTION_MAP.put("intogang", action14);
        IAction action15 = new RoleMoveAction();
        ParamTool.ACTION_MAP.put("move", action15);
        IAction petDepositAction = new PetDepositAction();
        ParamTool.ACTION_MAP.put("petDepositAction", petDepositAction);
        IAction action16 = new MountAction();
        ParamTool.ACTION_MAP.put("mount", action16);
        IAction action1666 = new CarAction();
        ParamTool.ACTION_MAP.put("car", action1666);

        IAction action17 = new PackChangeAction();
        ParamTool.ACTION_MAP.put("packchange", action17);
        IAction action18 = new FriendAction();
        ParamTool.ACTION_MAP.put("friend", action18);
        IAction action19 = new AddFriendAction();
        ParamTool.ACTION_MAP.put("addfriend", action19);
        IAction action20 = new DeleteFriendAction();
        ParamTool.ACTION_MAP.put("deletefriend", action20);
        IAction action21 = new FriendChatAction();
        ParamTool.ACTION_MAP.put("friendchat", action21);
        IAction action22 = new DeductiontaelAction();
        ParamTool.ACTION_MAP.put("deductiontael", action22);
        IAction action23 = new ChangeMapAction();
        ParamTool.ACTION_MAP.put("changemap", action23);
        IAction action24 = new GangCreateAction();
        ParamTool.ACTION_MAP.put("gangcreate", action24);
        IAction action25 = new GangApplyAction();
        ParamTool.ACTION_MAP.put("gangapply", action25);
        IAction action26 = new GangRetreatAction();
        ParamTool.ACTION_MAP.put("gangretreat", action26);
        IAction restGang = new GangRetreatrestAction();
        ParamTool.ACTION_MAP.put("gangchangerest", restGang);
        IAction action27 = new GangListAction();
        ParamTool.ACTION_MAP.put("ganglist", action27);
        IAction action28 = new GiveAction();
        ParamTool.ACTION_MAP.put("give", action28);
        IAction action29 = new GangShotAction();
        ParamTool.ACTION_MAP.put("gangshot", action29);
        IAction action30 = new GangAgreeAction();
        ParamTool.ACTION_MAP.put("gangagree", action30);
        IAction action31 = new GangRefuseAction();
        ParamTool.ACTION_MAP.put("gangrefuse", action31);
        IAction action32 = new GangAppointAction();
        ParamTool.ACTION_MAP.put("gangappoint", action32);
        IAction action33 = new GangChangeAction();
        ParamTool.ACTION_MAP.put("gangchange", action33);
        IAction action34 = new PawnAction();
        ParamTool.ACTION_MAP.put("pawn", action34);
        IAction action35 = new RetrieveAction();
        ParamTool.ACTION_MAP.put("retrieve", action35);
        IAction action36 = new PetChangeAction();
        ParamTool.ACTION_MAP.put("shuanimabipetchange", action36);
        IAction PetChangeSkillAction = new PetChangeSkillAction();
        ParamTool.ACTION_MAP.put("petchangeSkill", PetChangeSkillAction);
        IAction action37 = new TitleExpireAction();
        ParamTool.ACTION_MAP.put("titleexpirechange", action37);
        IAction action38 = new TitleChangeAction();
        ParamTool.ACTION_MAP.put("titlechange", action38);
        IAction action39 = new TitleListAction();
        ParamTool.ACTION_MAP.put("titlelist", action39);
        IAction action40 = new GetTitleListAction();
        ParamTool.ACTION_MAP.put("gettitlelist", action40);
        IAction action41 = new PackLockAction();
        ParamTool.ACTION_MAP.put("packlock", action41);
        IAction action42 = new PackGiftAction();
        ParamTool.ACTION_MAP.put("packgift", action42);
        IAction action43 = new MarryAction();
        ParamTool.ACTION_MAP.put("marry", action43);
        IAction action44 = new MakeLoveAction();
        ParamTool.ACTION_MAP.put("makelove", action44);
        IAction action45 = new PetInfoAction();
        ParamTool.ACTION_MAP.put("petinfo", action45);
        IAction action46 = new NpcComposeAction();
        ParamTool.ACTION_MAP.put("npccompose", action46);
        IAction action47 = new WitchComposeAction();
        ParamTool.ACTION_MAP.put("witchcompose", action47);
        IAction action48 = new PetReleaseAction();
        ParamTool.ACTION_MAP.put("petrelease", action48);
        IAction petreleasefp = new PetReleaseFPAction();
        ParamTool.ACTION_MAP.put("petreleasefp", petreleasefp);
        IAction action49 = new BabyReleaseAction();
        ParamTool.ACTION_MAP.put("babyrelease", action49);
        IAction action50 = new SummonPetAction();
        ParamTool.ACTION_MAP.put("summonpet", action50);
        IAction action51 = new RoleChangeAction();
        ParamTool.ACTION_MAP.put("rolechange", action51);
        IAction action52 = new FightRoundAction();
        ParamTool.ACTION_MAP.put("fig1", action52);
        IAction action53 = new FightbattleConnectionAction();
        ParamTool.ACTION_MAP.put("battleconnection", action53);
        IAction action54 = new FightingForeseeAction();
        ParamTool.ACTION_MAP.put("fig2", action54);
        IAction action55 = new FightingendAction();
        ParamTool.ACTION_MAP.put("fig6", action55);
        IAction action56 = new NpcCureAction();
        ParamTool.ACTION_MAP.put("npccure", action56);
        IAction action57 = new GangGiveMoneyAction();
        ParamTool.ACTION_MAP.put("givemoney", action57);
        IAction action58 = new PetAlchemyAction();
        ParamTool.ACTION_MAP.put("petalchemy", action58);
        IAction action59 = new BuyMingChaoAction();
        ParamTool.ACTION_MAP.put("buymingchao", action59);
        IAction action60 = new FightingRoundAction();
        ParamTool.ACTION_MAP.put("fig4", action60);
        IAction action61 = new RoleTransAction();
        ParamTool.ACTION_MAP.put("racialtransformation", action61);
        IAction action62 = new RoleLevelUpAction();
        ParamTool.ACTION_MAP.put("rolelevelup", action62);
        IAction action63 = new MountSkillStuAction();
        ParamTool.ACTION_MAP.put("addmountskill", action63);
        IAction action64 = new MountSkillDeleteAction();
        ParamTool.ACTION_MAP.put("missmountskill", action64);
        IAction action65 = new MountUpdateAction();
        ParamTool.ACTION_MAP.put("changemountvalue", action65);
        IAction action66 = new FlyUpdateAction();
        ParamTool.ACTION_MAP.put("changeflyvalue", action66);
        IAction action67 = new FlyAction();
        ParamTool.ACTION_MAP.put("fly", action67);
        IAction action68 = new KejuAction();
        ParamTool.ACTION_MAP.put("kejunpc", action68);
        IAction action69 = new KejuhuidaAction();
        ParamTool.ACTION_MAP.put("kejuhuida", action69);
        IAction action70 = new FlyGetAction();
        ParamTool.ACTION_MAP.put("flyget", action70);
        IAction action71 = new UseFlyAction();
        ParamTool.ACTION_MAP.put("usefly", action71);
        IAction action72 = new BabyAction();
        ParamTool.ACTION_MAP.put("baby", action72);
        IAction action73 = new UnMarryAction();
        ParamTool.ACTION_MAP.put("unmarry", action73);
        IAction action74 = new BabyBornAction();
        ParamTool.ACTION_MAP.put("babyborn", action74);
        IAction action75 = new BabyCustodayAction();
        ParamTool.ACTION_MAP.put("babycustoday", action75);
        IAction action76 = new UpdateLingAction();
        ParamTool.ACTION_MAP.put("updateling", action76);
        IAction action77 = new ChangeRoleNameAction();
        ParamTool.ACTION_MAP.put("changerolename", action77);
        IAction action78 = new NPCDialogAction();
        ParamTool.ACTION_MAP.put("npcdialog", action78);
        IAction action79 = new MiddleAction();
        ParamTool.ACTION_MAP.put("middle", action79);
        IAction action80 = new PrisonAction();
        ParamTool.ACTION_MAP.put("getout", action80);
        IAction action81 = new QuoteOutAction();
        ParamTool.ACTION_MAP.put("quoteout", action81);
        IAction action82 = new UpdaBabyAction();
        ParamTool.ACTION_MAP.put("updababy", action82);
        IAction action83 = new GangMonitorAction();
        ParamTool.ACTION_MAP.put("gangmonitor", action83);
        IAction action84 = new GangBattleAction();
        ParamTool.ACTION_MAP.put("gangbattle", action84);
        IAction action85 = new StallAction();
        ParamTool.ACTION_MAP.put("stall", action85);
        IAction stallListing = new StallListingAction();
        ParamTool.ACTION_MAP.put("listing", stallListing);
        IAction stallUpdate = new StallUpdateAction();
        ParamTool.ACTION_MAP.put("stallUpdate", stallUpdate);
        IAction action86 = new StallBuyAction();
        ParamTool.ACTION_MAP.put("stallbuy", action86);
        IAction action87 = new StallGetAction();
        ParamTool.ACTION_MAP.put("stallget", action87);
        IAction action88 = new MountReleaseAction();
        ParamTool.ACTION_MAP.put("mountrelease", action88);
        IAction action89 = new AddMonsterAction();
        ParamTool.ACTION_MAP.put("updatemonsters", action89);
        IAction action90 = new ObtainarticleAction();
        ParamTool.ACTION_MAP.put("obtainarticle", action90);
        IAction action91 = new DrawnitemsAction();
        ParamTool.ACTION_MAP.put("drawnitems", action91);
        IAction action92 = new itemAction();
        ParamTool.ACTION_MAP.put("item", action92);
        IAction action93 = new ThrowinarticleAction();
        ParamTool.ACTION_MAP.put("throwinarticle", action93);
        IAction action94 = new BindingMobileAction();
        ParamTool.ACTION_MAP.put("bindingmobile", action94);
        IAction action95 = new AccountStopAction();
        ParamTool.ACTION_MAP.put("accountstop", action95);
        IAction action96 = new OrderByRoleAction();
        ParamTool.ACTION_MAP.put("pankinglist", action96);
        IAction action97 = new LadderArenaAction();
        ParamTool.ACTION_MAP.put("laddArena", action97);
        IAction action98 = new BuyShopAction();
        ParamTool.ACTION_MAP.put("buygood", action98);
        IAction action99 = new UseRoleAction();
        ParamTool.ACTION_MAP.put("user", action99);
        IAction action100 = new PackRecordAction();
        ParamTool.ACTION_MAP.put("1", action100);
        IAction action101 = new enterGameAction();
        ParamTool.ACTION_MAP.put("enterGame", action101);
        IAction action102 = new RoleSystemAction();
        ParamTool.ACTION_MAP.put("roleSystem", action102);
        IAction action103 = new RolePrivateAction();
        ParamTool.ACTION_MAP.put("rolePrivate", action103);
        IAction action104 = new BookofchalgAction();
        ParamTool.ACTION_MAP.put("bookofchalg", action104);
        IAction action105 = new RefusechalgAction();
        ParamTool.ACTION_MAP.put("refusechalg", action105);
        IAction action106 = new LotteryAction();
        ParamTool.ACTION_MAP.put("getfivemsg", action106);
        IAction action107 = new ExchangeGoodsAction();
        ParamTool.ACTION_MAP.put("exchangegoods", action107);
        IAction action108 = new SuitComposeAction();
        ParamTool.ACTION_MAP.put("suitoperate", action108);
        IAction action109 = new QualityCAciton();
        ParamTool.ACTION_MAP.put("extrattroper", action109);
        IAction action110 = new AddGoodAction();
        ParamTool.ACTION_MAP.put("addgood", action110);
        IAction action111 = new HatchvalueAction();
        ParamTool.ACTION_MAP.put("hatchvalue", action111);
        IAction action112 = new HatchaddAction();
        ParamTool.ACTION_MAP.put("hatchadd", action112);
        IAction action113 = new RichMonitorAction();
        ParamTool.ACTION_MAP.put("richm", action113);
        IAction action114 = new ChatAction();
        ParamTool.ACTION_MAP.put("chat", action114);
        IAction action115 = new SearcahChatRoleIdAction();
        ParamTool.ACTION_MAP.put("searcahChatRoleId", action115);
        IAction action116 = new SearcahChatRoleNameAction();
        ParamTool.ACTION_MAP.put("searcahChatRoleName", action116);
        IAction action117 = new SearchChatRecordeAction();
        ParamTool.ACTION_MAP.put("searchChatRecorde", action117);
        IAction action118 = new NpcShopAction();
        ParamTool.ACTION_MAP.put("shop", action118);
        IAction action119 = new MyOrderSearchAction();
        ParamTool.ACTION_MAP.put("CBGSearch3", action119);
        IAction action120 = new AppointBuyAction();
        ParamTool.ACTION_MAP.put("CBGSearch4", action120);
        IAction action121 = new MyGoodsSearchAction();
        ParamTool.ACTION_MAP.put("CBGSearch5", action121);
        IAction action122 = new MessageSearchAction();
        ParamTool.ACTION_MAP.put("CBGSearch6", action122);
        IAction action123 = new CollectionSearchAction();
        ParamTool.ACTION_MAP.put("CBGSearch7", action123);
        IAction action124 = new GoodsControlAction();
        ParamTool.ACTION_MAP.put("CBGGood", action124);
        IAction action125 = new CollectionControlAction();
        ParamTool.ACTION_MAP.put("CBGCollect", action125);
        IAction action126 = new MessageControlAction();
        ParamTool.ACTION_MAP.put("CBGMes", action126);
        IAction action127 = new GoodsSearchAction();
        ParamTool.ACTION_MAP.put("CBGSearch1", action127);
        IAction action128 = new MyWaresSearchAction();
        ParamTool.ACTION_MAP.put("CBGSearch2", action128);
        IAction action129 = new GoodsShelfAction();
        ParamTool.ACTION_MAP.put("CBGShelf", action129);
        IAction action130 = new SearchChatRecordeAction();
        ParamTool.ACTION_MAP.put("searchChatRecorde", action130);
        IAction action131 = new GoodsBuyAction();
        ParamTool.ACTION_MAP.put("CBGBuy", action131);
        IAction action132 = new GoodsBackAction();
        ParamTool.ACTION_MAP.put("CBGBack", action132);
        IAction action133 = new ClickMonsterAction();
        ParamTool.ACTION_MAP.put("clickmonsters", action133);
        IAction action134 = new TransStateAction();
        ParamTool.ACTION_MAP.put("TransState", action134);
        IAction action135 = new TransGoodAction();
        ParamTool.ACTION_MAP.put("TransGood", action135);
        IAction action136 = new UsePetAction();
        ParamTool.ACTION_MAP.put("userpet", action136);
        IAction action137 = new MonitorAction();
        ParamTool.ACTION_MAP.put("Monitor", action137);
        IAction action138 = new UseMountAction();
        ParamTool.ACTION_MAP.put("usermount", action138);
        IAction action139 = new UseLingAction();
        ParamTool.ACTION_MAP.put("userling", action139);
        IAction action140 = new UseBabyAction();
        ParamTool.ACTION_MAP.put("userbaby", action140);
        IAction action141 = new UseCardAction();
        ParamTool.ACTION_MAP.put("usercard", action141);
        IAction action142 = new TaskAction();
        ParamTool.ACTION_MAP.put("taskN", action142);
        IAction action143 = new FightQlAction();
        ParamTool.ACTION_MAP.put("fig8", action143);
        IAction action144 = new PhoneBangAction();
        ParamTool.ACTION_MAP.put("PhoneBang", action144);
        IAction action145 = new UnPhoneBangAction();
        ParamTool.ACTION_MAP.put("UnPhoneBang", action145);
        IAction action146 = new PhoneNumberIsNoGetAction();
        ParamTool.ACTION_MAP.put("PhoneNumberIsNoGet", action146);
        IAction action147 = new GetVipGradePackAction();
        ParamTool.ACTION_MAP.put("Getvipgradepack", action147);
        IAction action148 = new VipGradeSureAction();
        ParamTool.ACTION_MAP.put("Vipgradesure", action148);
        IAction action149 = new PayDayGradePayAction();
        ParamTool.ACTION_MAP.put("Paydaygradepay", action149);
        IAction action150 = new PayDayGradeSureAction();
        ParamTool.ACTION_MAP.put("Paydaygradesure", action150);
        IAction action151 = new DayForWeekGradeGetAction();
        ParamTool.ACTION_MAP.put("Dayforweekgradeget", action151);
        IAction action152 = new DayForWeekGradeSureAction();
        ParamTool.ACTION_MAP.put("Dayforweekgradesure", action152);
        IAction action153 = new DayForOneGetAction();
        ParamTool.ACTION_MAP.put("Dayforoneget", action153);
        IAction action154 = new DayForOneSureAction();
        ParamTool.ACTION_MAP.put("Dayforonesure", action154);
        IAction action155 = new ChongJiPackGetAction();
        ParamTool.ACTION_MAP.put("chongjipackget", action155);
        IAction action156 = new ChongJiPackSureAction();
        ParamTool.ACTION_MAP.put("Chongjipacksure", action156);
        IAction action157 = new ChongJiPackOpenAction();
        ParamTool.ACTION_MAP.put("Chongjipackopen", action157);
        IAction action158 = new PayLJGradePayAction();
        ParamTool.ACTION_MAP.put("PayLJgradesure", action158);
        IAction action159 = new PayLJGradeSureAction();
        ParamTool.ACTION_MAP.put("PayLJgradesure", action159);
        IAction action160 = new LimitedTimeLshopAction();
        ParamTool.ACTION_MAP.put("LimitedTimeShop", action160);
        IAction action161 = new SceneAction();
        ParamTool.ACTION_MAP.put("scene", action161);
        IAction action162 = new UsePalAction();
        ParamTool.ACTION_MAP.put("userpal", action162);
        IAction action163 = new ShopPriceAction();
        ParamTool.ACTION_MAP.put("shopPrice", action163);
        IAction action164 = new TeamEnlistAction();
        ParamTool.ACTION_MAP.put("enlist", action164);
        IAction action165 = new TeamCreateAction();
        ParamTool.ACTION_MAP.put("team1", action165);
        IAction action166 = new TeamApplyAction();
        ParamTool.ACTION_MAP.put("team2", action166);
        IAction action167 = new TeamStateAction();
        ParamTool.ACTION_MAP.put("team4", action167);
        IAction action168 = new TeamOperateAction();
        ParamTool.ACTION_MAP.put("team5", action168);
        IAction action169 = new TeamApplyListAction();
        ParamTool.ACTION_MAP.put("team6", action169);
        IAction action170 = new FindWayAction();
        ParamTool.ACTION_MAP.put("findway", action170);
        IAction action171 = new ConfirmAciton();
        ParamTool.ACTION_MAP.put("confirm", action171);
        IAction action172 = new OneArenaAction();
        ParamTool.ACTION_MAP.put("oneArena", action172);
        IAction action173 = new TeamArenaAction();
        ParamTool.ACTION_MAP.put("teamArena", action173);
        IAction action174 = new LaborAction();
        ACTION_MAP.put(AgreementUtil.labor, action174);
        IAction action175 = new VIconAction();
        ParamTool.ACTION_MAP2.put("fig1", ParamTool.ACTION_MAP.get("fig1"));
        ParamTool.ACTION_MAP2.put("fig4", ParamTool.ACTION_MAP.get("fig4"));
        ParamTool.ACTION_MAP2.put("fig7", ParamTool.ACTION_MAP.get("fig7"));
        ParamTool.ACTION_MAP2.put("move", ParamTool.ACTION_MAP.get("move"));
        IAction action176 = new SalesGoodsChangeOrder();
        ParamTool.ACTION_MAP.put("salesGoodsChangeOrder_inter", action176);
        IAction action177 = new SaleGoodsStatues();
        ParamTool.ACTION_MAP.put("saleGoodsStatues_inter", action177);
        IAction action178 = new GoodsBuy();
        ParamTool.ACTION_MAP.put("goodsBuy_inter", action178);
        IAction action179 = new Payreturn();
        ParamTool.ACTION_MAP.put(AgreementUtil.PAYRETURN, action179);
        ParamTool.ACTION_MAP.put("findDrop", new FindDropAction());
        ParamTool.ACTION_MAP.put("getEgg", new EggAction());
        ParamTool.ACTION_MAP.put("hjsl", new HjslAction());
        GoodsExchangeAction action180 = new GoodsExchangeAction();
        ParamTool.ACTION_MAP.put("GOODSFORGOODS", action180);
        ParamTool.ACTION_MAP.put("findDrop", new FindDropAction());
        ParamTool.ACTION_MAP.put("hjsl", new HjslAction());
        ParamTool.ACTION_MAP.put("lingxi", new LxAction());
        ParamTool.ACTION_MAP.put("getEgg", new EggAction());
        ParamTool.ACTION_MAP.put("lingxi", new LxAction());
        ParamTool.ACTION_MAP.put("qd", new QianDaoAction());
        ParamTool.ACTION_MAP.put("GMSHOP", new GMshopItemAction());
        ParamTool.ACTION_MAP.put("expAdd", new expAddAction());
        ParamTool.ACTION_MAP.put("QMJC", new LotteryRoleAction());
        IAction action181 = new Account_Login();
        ParamTool.ACTION_MAP.put("ACCOUNT_LOGIN", action181);
        ParamTool.ACTION_MAP.put("updateXianyu", new updateXianyuAction());
        ParamTool.ACTION_MAP.put("sellxianyu", new SellXianYuAction());
        ParamTool.ACTION_MAP.put("shaoxiang", new ShaoXiangAction());
        ParamTool.ACTION_MAP.put("AutoTask", new AutoTaskAction());
        ParamTool.ACTION_MAP.put("setlianghao", new LiangHaoAction());
        ParamTool.ACTION_MAP.put("lottery", new LotteryNineAction());
        ParamTool.ACTION_MAP.put("zxpack", new ZxpackNineAction());
        ParamTool.ACTION_MAP.put("selllianghao", new SellLiangHaoAction());
        ParamTool.ACTION_MAP.put("HDX", new HDXRoleAction());
        ParamTool.ACTION_MAP.put("GUA", new JieGuaAction());
        IAction action182 = new MountShouHuAction();
        ParamTool.ACTION_MAP.put("shouhuPMxy", action182);
        ParamTool.ACTION_MAP.put("QzCUNQU", new QZCUNQUMoneyAction());
        //IAction roleDayDrawAction = new RoleDayDrawAction();
        //ACTION_MAP.put(AgreementUtil.ROLEDAYDRAW, roleDayDrawAction);
        IAction roleAchievemAction = new RoleAchievemAction();
        ACTION_MAP.put(AgreementUtil.ROLEACHIEVE, roleAchievemAction);
        ACTION_MAP.put(AgreementUtil.fuben, new FuBenAction());
        IAction roleDayDrawAction = new RoleDayDrawAction();
        ACTION_MAP.put(AgreementUtil.ROLEDAYDRAW, roleDayDrawAction);
    }
    
    static {
        ACTION_MAP = new HashMap<>();
        ACTION_MAP2 = new HashMap<>();
    }
}
